addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.3.4")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                % "5.5.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"              % "0.9.14")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"            % "1.5.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                   % "0.3.7")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"              % "0.15.0")
